### ISSUE TITLE
refactor to use ruby-git

### ISSUE THREAD

**Issue by zilkey** [zilkey/auto_tagger#14]

**Comment by jpignata** [comment]
Looks like grit is actually the One True Library: http://wiki.github.com/schacon/ruby-git

**Comment by zilkey** [comment]
The last two projects (original Grit and Ruby-Git) both claimed to be the one true library.  I'd like to wait six months and see what happens before spending time putting this in the codebase.  I'll re-open this ticket when the dust settles.
